blank_issues_enabled: false
contact_links:
  - name: Diskussion / Fragen
    url: https://github.com/DDA1010/hydroponic-control/discussions
    about: Für allgemeine Fragen bitte die Discussions nutzen
